# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QhlHIZ9JqHrkVPEu6eP0jbBnQ9CjcwWd
"""

import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import tensorflow as tf
import random

from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from keras.preprocessing.image import ImageDataGenerator

from sklearn.metrics import classification_report, log_loss, accuracy_score
from sklearn.model_selection import train_test_split
from tqdm import tqdm

train_dir = '/content/drive/MyDrive/marble/dataset/train/'
test_dir = '/content/drive/MyDrive/marble/dataset/test/'

Name=[]
for file in os.listdir(train_dir):
    Name+=[file]
print(Name)
print(len(Name))

N=[]
for i in range(len(Name)):
    N+=[i]
    
normal_mapping=dict(zip(Name,N)) 
reverse_mapping=dict(zip(N,Name))

trainx0=[]
trainy0=[]
count=0
for file in Name:
    path=os.path.join(train_dir,file)
    for im in tqdm(os.listdir(path)):
        image=load_img(os.path.join(path,im), grayscale=False, color_mode='rgb', target_size=(48,48))
        image=img_to_array(image)
        image=image/255.0
        trainx0.append(image)
        trainy0.append(count)
    count=count+1

testx0=[]
testy0=[]
count=0
for file in Name:
    path=os.path.join(test_dir,file)
    for im in tqdm(os.listdir(path)):
        image=load_img(os.path.join(path,im), grayscale=False, color_mode='rgb', target_size=(48,48))
        image=img_to_array(image)
        image=image/255.0
        testx0.append(image)
        testy0.append(count)
    count=count+1

trainx1=np.array(trainx0)
trainy1=np.array(trainy0)
testx1=np.array(testx0)
testy1=np.array(testy0)

trainy2=to_categorical(trainy1)
y_train=np.array(trainy2)

X_train=np.array(trainx1).reshape(-1,48,48,3)
X_test=np.array(testx1).reshape(-1,48,48,3)

trainx,testx,trainy,testy=train_test_split(X_train,y_train,test_size=0.2,random_state=44)

print(trainx.shape)
print(testx.shape)
print(trainy.shape)
print(testy.shape)

datagen = ImageDataGenerator(horizontal_flip=True,vertical_flip=True,rotation_range=20,zoom_range=0.2,
                        width_shift_range=0.2,height_shift_range=0.2,shear_range=0.1,fill_mode="nearest")

pretrained_model3 = tf.keras.applications.DenseNet201(input_shape=(48,48,3),include_top=False,weights='imagenet',pooling='avg')
pretrained_model3.trainable = False

inputs3 = pretrained_model3.input
x3 = tf.keras.layers.Dense(128, activation='relu')(pretrained_model3.output)
outputs3 = tf.keras.layers.Dense(4, activation='softmax')(x3)
model = tf.keras.Model(inputs=inputs3, outputs=outputs3)

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

his=model.fit(datagen.flow(trainx,trainy,batch_size=32),validation_data=(testx,testy),epochs=20)

y_pred=model.predict(testx)
pred=np.argmax(y_pred,axis=1)
ground = np.argmax(testy,axis=1)
print(classification_report(ground,pred))

get_acc = his.history['accuracy']
value_acc = his.history['val_accuracy']
get_loss = his.history['loss']
validation_loss = his.history['val_loss']

epochs = range(len(get_acc))
plt.plot(epochs, get_acc, 'r', label='Accuracy of Training data')
plt.plot(epochs, value_acc, 'b', label='Accuracy of Validation data')
plt.title('Training vs validation accuracy')
plt.legend(loc=0)
plt.figure()
plt.show()

epochs = range(len(get_loss))
plt.plot(epochs, get_loss, 'r', label='Loss of Training data')
plt.plot(epochs, validation_loss, 'b', label='Loss of Validation data')
plt.title('Training vs validation loss')
plt.legend(loc=0)
plt.figure()
plt.show()

model.save("/content/drive/MyDrive/model.h5")

import tensorflow as tf
from keras.models import load_model

model=load_model("/content/drive/MyDrive/model.h5")

converter = tf.lite.TFLiteConverter.from_keras_model(model)

lite_model=converter.convert()

with open("lite_model.tflite","wb") as f:
  f.write(lite_model)